# Generated by Django 3.2.4 on 2021-09-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('email', 'Email'), ('checkbox', 'Checkbox'), ('color', 'Color'), ('date', 'Date'), ('hidden', 'Hidden'), ('password', 'Password'), ('radio', 'Radio'), ('textarea', 'Textarea'), ('select', 'Select')], max_length=255)),
            ],
        ),
    ]
