# Generated by Django 3.2.7 on 2021-09-03 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0003_alter_formfield_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='From',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('email', 'Email'), ('checkbox', 'Checkbox'), ('color', 'Color'), ('date', 'Date'), ('hidden', 'Hidden'), ('password', 'Password'), ('radio', 'Radio'), ('textarea', 'Textarea'), ('select', 'Select')], max_length=255)),
                ('value', models.JSONField(blank=True, null=True)),
                ('order', models.IntegerField()),
                ('form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form', to='form_builder.from')),
            ],
        ),
    ]
